import {
  Users,
  Code,
  Briefcase,
  DollarSign,
  CalendarDays,
  Star,
  type LucideIcon,
  MessageSquare,
  Mic,
  Eye,
  Workflow,
  Cloud,
  Database,
  Monitor,
  Cpu,
  Target,
  Lightbulb,
  Heart,
  Zap,
  Clock,
  HeadphonesIcon,
  TrendingUp,
  Sparkles,
  Shield,
  Scale,
  Globe,
  Palette,
  Home,
  FileText,
  UserCheck,
  Video,
  GraduationCap,
  Search,
} from "lucide-react"

// Map of icon names to their Lucide React components
export const iconMap: { [key: string]: LucideIcon } = {
  Users: Users,
  Code: Code,
  Briefcase: Briefcase,
  DollarSign: DollarSign,
  CalendarDays: CalendarDays,
  Star: Star,
  MessageSquare: MessageSquare,
  Mic: Mic,
  Eye: Eye,
  Workflow: Workflow,
  Cloud: Cloud,
  Database: Database,
  Monitor: Monitor,
  Cpu: Cpu,
  Target: Target,
  Lightbulb: Lightbulb,
  Heart: Heart,
  Zap: Zap,
  Clock: Clock,
  HeadphonesIcon: HeadphonesIcon,
  TrendingUp: TrendingUp,
  Sparkles: Sparkles,
  Shield: Shield,
  Scale: Scale,
  Globe: Globe,
  Palette: Palette,
  Home: Home,
  FileText: FileText,
  UserCheck: UserCheck,
  Video: Video,
  GraduationCap: GraduationCap,
  Search: Search,
}

// Array of available icon names for dropdowns
export const availableIcons = Object.keys(iconMap)
